services:
  backend:
    build: ./backend
    container_name: edutech-backend
    ports:
      - "4000:4000"
    networks:
      - edutech-net

  frontend:
    build: ./frontend
    container_name: edutech-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - edutech-net

networks:
  edutech-net:
    driver: bridge
